### PR TITLE
Add the librpma example (R)

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: 0 of 8 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: 0 of 8 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: 0 of 8 files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/1#-MjcPwR20_O7ahhB21UG:-MjcL6Gk3xFbWKNq_KUz:bcackhf) (no related file):*
I think we need along with this example a script allowing us to configure the SoftRoCE.
Please add it.

---
___
*[examples/R/CMakeLists.txt, line 36 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/1#-MjcMyBN6G2zucHZxYnB:-MjcMyBN6G2zucHZxYnC:b-snyl5s) ([raw file](https://github.com/ldorau/2021-04-21/blob/834e12d361e735659e4621713565204f7c27efaa/examples/R/CMakeLists.txt#L36)):*
> ```CMake
> 
> add_flag(-Wall)
> add_flag(-Werror)
> ```

This one is interesting. Since these flags are not set when you try to build an example solo from the librpma repository, are they?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/1#-MjcPwR20_O7ahhB21UG:-MjcaMVxAo9NYVGaxIZc:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we need along with this example a script allowing us to configure the SoftRoCE.
Please add it.
</blockquote></details>

Done.

---
___
*[examples/R/CMakeLists.txt, line 36 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/1#-MjcMyBN6G2zucHZxYnB:-MjcWEhA31wLkpafTULY:b-xj6816) ([raw file](https://github.com/ldorau/2021-04-21/blob/834e12d361e735659e4621713565204f7c27efaa/examples/R/CMakeLists.txt#L36)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This one is interesting. Since these flags are not set when you try to build an example solo from the librpma repository, are they?
</blockquote></details>

I have added them here.

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/tools/README.md, line 3 at r4](https://reviewable.io/reviews/ldorau/2021-04-21/1#-Mjce7bE9qvOwIssWxyZ:-Mjce7bE9qvOwIssWxy_:b-ya5cn6) ([raw file](https://github.com/ldorau/2021-04-21/blob/842f9555f96be275cb25623f5ce6d6f24ec64db5/examples/R/tools/README.md#L3)):*
> ```Markdown
> # Tools
> 
> This directory contains useful tool:
> ```

a useful tool

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/R/tools/README.md, line 3 at r4](https://reviewable.io/reviews/ldorau/2021-04-21/1#-Mjce7bE9qvOwIssWxyZ:-Mjcg6BfCxy09cWS-xeE:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/842f9555f96be275cb25623f5ce6d6f24ec64db5/examples/R/tools/README.md#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a useful tool
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1#-:-MjdEmJpDHIGVtNx-6qe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 2 of 3 files at r3, 1 of 3 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 8 files at r1, 2 of 3 files at r3, 1 of 3 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/1#-:-Mk21CC-BlelZaC9khgQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
