### PR TITLE
example R: add sleep 1 before starting the client

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/24)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/24)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/24#-MlKJkfKBuiH943lhR-U:-MlKJkfKBuiH943lhR-V:b-14czcj) (no related file):*
https://github.com/ldorau/2021-04-21/blob/devel/examples/R/run_test_rping.sh#L9  ?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/24)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/24#-MlKJkfKBuiH943lhR-U:-MlKK5As9BOM0xxYEoTp:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

https://github.com/ldorau/2021-04-21/blob/devel/examples/R/run_test_rping.sh#L9  ?
</blockquote></details>

Done.

---

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/24#-:-MlKMOjFEwYlas1OHv4L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/24#-:-MlKOurm0Yezvc6hmq36:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
