### PR TITLE
example R: move malloc_aligned() to client.c

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/35)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/35)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/connection.h, line 18 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/35#-Mo3XRZb2TVTXpMC1Hiv:-Mo3XRZb2TVTXpMC1Hiw:b-6guyxj) ([raw file](https://github.com/ldorau/2021-04-21/blob/92d19aed0778ac980fc81ff64caa211f0d4df706/examples/R/connection.h#L18)):*
> ```objc
> #define PMEM_MIN_SIZE	(MAX_USERS * 4 * KILOBYTE) /* 4KiB for each user */
> 
> #define NO_PMEM_MSG "No <pmem-path> provided. Using DRAM instead.\n"
> ```

Not a part of this change.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/35)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/R/connection.h, line 18 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/35#-Mo3XRZb2TVTXpMC1Hiv:-Mo3nRc-22E4lokWBmoS:bg8lxfr) ([raw file](https://github.com/ldorau/2021-04-21/blob/92d19aed0778ac980fc81ff64caa211f0d4df706/examples/R/connection.h#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not a part of this change.
</blockquote></details>

Two pull requests got mixed by accident ... 

Fixed.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/35#-:-Mo3p65y7zz4QJ15Cu29:bnfp4nl)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/35#-:-Mo3qeu4534bed8As1D8:bg7igkv)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/35#-:-Mo3tp_z6mvBAOS7AIhr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/35#-:-Mo3urSk2_8JE4U_7Enq:bg7igk9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/35#-:-Mo3w1F17DrDsx0YIoqn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
