### PR TITLE
example R: update README

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/28)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/28#-:-MnfOe1L-HUJw48B3GE5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/28)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/R/README.md, line 12 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/28#-MnfStAKEmQohKDbQN5V:-MnfStAKEmQohKDbQN5W:b-dgr3gk) ([raw file](https://github.com/ldorau/2021-04-21/blob/58713571b00b86dd20bb4fb5949b57c5b7e83f55/examples/R/README.md#L12)):*
> ```Markdown
> the server's memory regions registered as a reading source and a writing destination.
> The client performs the RDMA read from the remote memory region to the local memory region,
> then it writes a new data to the local memory region and performs the RDMA write
> ```

~~a~~ new
___
*[examples/R/README.md, line 16 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/28#-MnfTUv34NCw9xNgV2bI:-MnfTUv34NCw9xNgV2bJ:b-7evx63) ([raw file](https://github.com/ldorau/2021-04-21/blob/58713571b00b86dd20bb4fb5949b57c5b7e83f55/examples/R/README.md#L16)):*
> ```Markdown
> 
> **Note**: The server requires the correct <user-id> argument in order to use
> a different part of persistent memory than other users do.
> ```

The server requires **a unique** \<user-id\> argument in order to use a different part of persistent memory **which is shared by all the server instances running on the same \<pmem-path\>**. **\<user-id\> is also used to pick a unique TCP port.**

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/28)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[examples/R/README.md, line 12 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/28#-MnfStAKEmQohKDbQN5V:-MnfV1W9-039p2g4Mx0U:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/58713571b00b86dd20bb4fb5949b57c5b7e83f55/examples/R/README.md#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~a~~ new
</blockquote></details>

Done.
___
*[examples/R/README.md, line 16 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/28#-MnfTUv34NCw9xNgV2bI:-MnfV1otBo4jBgkuAYwY:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/58713571b00b86dd20bb4fb5949b57c5b7e83f55/examples/R/README.md#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The server requires **a unique** \<user-id\> argument in order to use a different part of persistent memory **which is shared by all the server instances running on the same \<pmem-path\>**. **\<user-id\> is also used to pick a unique TCP port.**
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/28#-:-MnfVMFY1eK4eI7XbsaM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
