### PR TITLE
example R: add prefixes to messages

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/42)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/42#-:-Mo8N_se6aJtbgOb826a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/42)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/42#-Mo9GTQ-3-hUWXEVqa2D:-Mo9GTQ0Bj3xnmawjUni:b-5v1ar0) (no related file):*
in case of errors Client: => Client: error:, the same for Server:

---

**Comment by ldorau** [comment]
Incorporated into https://github.com/ldorau/2021-04-21/pull/44

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/42)* status: all files reviewed, 1 unresolved discussion

**Pull request closed without merging**
