### PR TITLE
example R: add devdax support

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25)* status: all files reviewed, 13 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOhc4y2L4DHPScvFlv:-MlOhc4y2L4DHPScvFlw:b-8cioiv) (no related file):*
Please rebase.

---
___
*[examples/R/run_main.sh, line 6 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOiMY419AVz95GPmxa:-MlOiMY419AVz95GPmxb:b89o9gn) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/run_main.sh#L6)):*
> ```Shell
> #
> 
> if [ ! -c /${DEV_DAX} ]; then
> ```

Why "/"?
___
*[examples/R/run_main.sh, line 7 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOikaZ4Ocel4dyRE_H:-MlOikaZ4Ocel4dyRE_I:b-7amgtl) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/run_main.sh#L7)):*
> ```Shell
> 
> if [ ! -c /${DEV_DAX} ]; then
>         echo "Error: \"${DEV_DAX}\" devdax device not found (DEV_DAX environment variable)"
> ```

For me, "devdax device" sounds like you are saying "device" twice. I have tried to look up how it should be called. It seems it either should be called "davdax" or "Device DAX". What do you think?

Ref: https://pmem.io/glossary/#device-dax
___
*[examples/R/run_main.sh, line 11 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOjE2cA4Q-E6dId6eB:-MlOjE2cA4Q-E6dId6eC:bmb9hue) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/run_main.sh#L11)):*
> ```Shell
> fi
> 
> echo "DAX device: ${DEV_DAX}"
> ```

Device DAX
___
*[examples/R/server.c, line 15 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOjNpBBDY7aWmeIj1i:-MlOjNpBBDY7aWmeIj1j:bf2eu79) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L15)):*
> ```C
> #include "connection.h"
> 
> #define USAGE_STR	"usage: %s <server_address> <port> [<pmem-path> <user-id> [direct-pmem-write]]\n"
> ```

There should be no other way than `direct-pmem-write=on`. I think we should simplify this example by dropping the opposite condition.
___
*[examples/R/server.c, line 23 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOn4zq6J3qovVy2PWh:-MlOjmPZ7KimpN7hcRML:b-hkudyw) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L23)):*
> ```C
> 
> void
> error_on_wrong_usage(int cond, const char * argv0)
> ```

`const char *argv0`
___
*[examples/R/server.c, line 54 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOknK0A6zZo8uV7A7i:-MlOknK17sqaUUUAPFsO:bt21w1f) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L54)):*
> ```C
> 	int user_id = 1;
> 
> 	if (argc >= 4) {
> ```

Since it is now clear we can easily use Device DAX-based server we should drop the DRAM path.
___
*[examples/R/server.c, line 80 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOl3IyEUcmPEbsX1da:-MlOl3IyEUcmPEbsX1db:b2heqyl) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L80)):*
> ```C
> 
> 		/* check if PMem has minimum required size */
> 		if (mr_size < PMEM_MIN_SIZE) {
> ```

I don't like continuing to call it "memory region size" aka `mr_size`. It may be confusing.
At this point, it should be called the PMem size (`pmem_size`?).
___
*[examples/R/server.c, line 87 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOlbqaERa5BojGJuFn:-MlOlbqaERa5BojGJuFo:bswzphk) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L87)):*
> ```C
> 		}
> 
> 		/* register a separate 4KiB of PMem for each user */
> ```

`dedicate a separate 4KiB of PMem for each user`

No registration takes place here.
___
*[examples/R/server.c, line 96 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOluajEDn8tTohKZOC:-MlOluajEDn8tTohKZOD:b2czgfz) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L96)):*
> ```C
> 		(void) fprintf(stderr, NO_PMEM_MSG);
> 		mr_size = KILOBYTE;
> 		mr_ptr = malloc_aligned(mr_size);
> ```

I'm for dropping this path as a whole.
But, if it will remain I am for allocating 4KiB instead of just a single one.
Otherwise, the user ends up with either 1 or 4 KiB without any obvious reason.
___
*[examples/R/server.c, line 108 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOmKdB56EXadGIqQAr:-MlOmKdB56EXadGIqQAs:bm6tqc2) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L108)):*
> ```C
> 
> 	/* set and print the initial content */
> 	char *data_ptr = (char *)mr_ptr;
> ```

Do we even need `mr_ptr` of type `void *`?
___
*[examples/R/server.c, line 125 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOmW9l0k8xJpoY5dTA:-MlOmW9l0k8xJpoY5dTB:b-vaeaqi) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L125)):*
> ```C
> 			goto err_free;
> 		}
> 	}
> ```

In my opinion, It should be assumed this is the case.
___
*[examples/R/server.c, line 163 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOmcIiBUshyLkno6Nj:-MlOmcIiBUshyLkno6Nk:b-tyx4ve) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L163)):*
> ```C
> 	/* calculate data for the client write */
> 	struct common_data data = {0};
> 	data.data_offset = 0;
> ```

`data_offset` is no longer needed at all.
It should be removed from `struct common_data`.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/R/server.c, line 15 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOjNpBBDY7aWmeIj1i:-MlOoNG06XiQV3v8_r9g:b32v57) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

There should be no other way than `direct-pmem-write=on`. I think we should simplify this example by dropping the opposite condition.
</blockquote></details>

+1
___
*[examples/R/server.c, line 23 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOn4zq6J3qovVy2PWh:-MlOoOYd-B7ombtJLlZr:b3bx1f6) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`const char *argv0`
</blockquote></details>

can we have only a long macro definition instead of macro = function?
___
*[examples/R/server.c, line 54 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOknK0A6zZo8uV7A7i:-MlOosO96SRg7d8_FpYb:b32v57) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since it is now clear we can easily use Device DAX-based server we should drop the DRAM path.
</blockquote></details>

+1

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25)* status: 0 of 5 files reviewed, 13 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOhc4y2L4DHPScvFlv:-MlOwKu75q0_6ZWWYz12:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

Done.

---
___
*[examples/R/run_main.sh, line 6 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOiMY419AVz95GPmxa:-MlOowqN728lK0II_Iic:b-vyach) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/run_main.sh#L6)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why "/"?
</blockquote></details>

So that it works for empty $DEV_DAX too. It is based on the assumption that $DEV_DAX is always an absolute path. In this way we do not need to check if it is empty.
___
*[examples/R/run_main.sh, line 7 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOikaZ4Ocel4dyRE_H:-MlOps137tQz_chzWVV-:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/run_main.sh#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

For me, "devdax device" sounds like you are saying "device" twice. I have tried to look up how it should be called. It seems it either should be called "davdax" or "Device DAX". What do you think?

Ref: https://pmem.io/glossary/#device-dax
</blockquote></details>

Done.
___
*[examples/R/run_main.sh, line 11 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOjE2cA4Q-E6dId6eB:-MlOpxPd4DvVASYbda8E:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/run_main.sh#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Device DAX
</blockquote></details>

Done.
___
*[examples/R/server.c, line 15 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOjNpBBDY7aWmeIj1i:-MlOqj6hDWZ_mnpo4InS:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[examples/R/server.c, line 23 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOn4zq6J3qovVy2PWh:-MlOrPXVAXt91428Kxem:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

can we have only a long macro definition instead of macro = function?
</blockquote></details>

Done.
___
*[examples/R/server.c, line 54 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOknK0A6zZo8uV7A7i:-MlOsglQ635INijkDULp:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[examples/R/server.c, line 80 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOl3IyEUcmPEbsX1da:-MlOudWI4CsLZhTKGXD-:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L80)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't like continuing to call it "memory region size" aka `mr_size`. It may be confusing.
At this point, it should be called the PMem size (`pmem_size`?).
</blockquote></details>

Done.
___
*[examples/R/server.c, line 87 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOlbqaERa5BojGJuFn:-MlOueZP6mDdBZPp7UXo:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`dedicate a separate 4KiB of PMem for each user`

No registration takes place here.
</blockquote></details>

Done.
___
*[examples/R/server.c, line 96 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOluajEDn8tTohKZOC:-MlOumB90U76yeC1kOXX:ba3dfob) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L96)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm for dropping this path as a whole.
But, if it will remain I am for allocating 4KiB instead of just a single one.
Otherwise, the user ends up with either 1 or 4 KiB without any obvious reason.
</blockquote></details>

Removed
___
*[examples/R/server.c, line 108 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOmKdB56EXadGIqQAr:-MlOvSG17O0JOo_EA_vG:bebv8ec) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do we even need `mr_ptr` of type `void *`?
</blockquote></details>

No.

Done.
___
*[examples/R/server.c, line 125 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOmW9l0k8xJpoY5dTA:-MlOvrND6C-Gsc83TYNL:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L125)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In my opinion, It should be assumed this is the case.
</blockquote></details>

Done.
___
*[examples/R/server.c, line 163 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOmcIiBUshyLkno6Nj:-MlOwImd3sCDNnyfLPqo:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/47dd3fd09aceba9c42849db1675ea32187932ec1/examples/R/server.c#L163)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`data_offset` is no longer needed at all.
It should be removed from `struct common_data`.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[examples/R/connection.h, line 24 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOy3_N12rRFGLV2XO6:-MlOy3_N12rRFGLV2XO7:b-kgecmb) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/connection.h#L24)):*
> ```objc
>  * for rdma_connect() in case of RDMA_PS_TCP (56 bytes).
>  */
> #define DESCRIPTORS_MAX_SIZE 24
> ```

Has to be adjusted.
___
*[examples/R/run_main.sh, line 12 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlP1KjbEDnGH5HeWVCM:-MlP1KjbEDnGH5HeWVCN:bk3kl5x) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/run_main.sh#L12)):*
> ```Shell
> 
> echo "Device DAX: ${DEV_DAX}"
> ls -al ${DEV_DAX}
> ```

How does the output look like?
___
*[examples/R/server.c, line 18 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlP1Yx-4M2OwCoG3KDY:-MlP1Yx-4M2OwCoG3KDZ:bpouv6g) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L18)):*
> ```C
> #define INIT_STR	"This is the initial server string."
> 
> #define ERROR_ON_WRONG_USAGE(cond)				\
> ```

I'm not sure but that isn't the case our cstyle encourages doing just ` \` (space at the front)?
___
*[examples/R/server.c, line 56 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOywwGBfdm1FvRrm6L:-MlOywwGBfdm1FvRrm6M:b-pkbzbq) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L56)):*
> ```C
> 	if (pmem_ptr == NULL) {
> 		(void) fprintf(stderr, "pmem_map_file() for %s "
> 				"failed\n", path);
> ```

The string won't fit into the previous line?
___
*[examples/R/server.c, line 63 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOz0Tq0CmHKmu1lIcF:-MlOz0Tq0CmHKmu1lIcG:bn6k4w0) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L63)):*
> ```C
> 	if (!is_pmem) {
> 		(void) fprintf(stderr, "%s is not an actual PMEM\n",
> 			path);
> ```

Won't fit into the previous line?
___
*[examples/R/server.c, line 90 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlP2i67BszwnTJhZDo6:-MlP2i67BszwnTJhZDo7:bj26uy2) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L90)):*
> ```C
> 
> 	/* set and print the initial content */
> 	strncpy(mr_ptr, INIT_STR, KILOBYTE);
> ```

`4 * KILOBYTE` :grin: 
___
*[examples/R/server.c, line 99 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOzzcc47KBPy3AB3z0:-MlOzzcc47KBPy3AB3z1:bgf36hj) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L99)):*
> ```C
> 
> 	/* configure peer's direct write to pmem support */
> 	ret = rpma_peer_cfg_set_direct_write_to_pmem(pcfg, 1 /* true */);
> ```

Simply `true` should be enough.

Ref: http://pmem.io/rpma/manpages/master/rpma_peer_cfg_set_direct_write_to_pmem.3

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[examples/R/connection.h, line 24 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOy3_N12rRFGLV2XO6:-MlP5sMi4aYwchmls9Jl:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/connection.h#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Has to be adjusted.
</blockquote></details>

Done.
___
*[examples/R/run_main.sh, line 12 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlP1KjbEDnGH5HeWVCM:-MlP3oSx5-CuRnroJT0b:b-fib5vq) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/run_main.sh#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

How does the output look like?
</blockquote></details>

It has left from debug version, removed.
___
*[examples/R/server.c, line 18 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlP1Yx-4M2OwCoG3KDY:-MlP40HyEV5nJs_vZkH5:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not sure but that isn't the case our cstyle encourages doing just ` \` (space at the front)?
</blockquote></details>

Done.
___
*[examples/R/server.c, line 56 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOywwGBfdm1FvRrm6L:-MlP3So2AMmp0c2DuVd9:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L56)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The string won't fit into the previous line?
</blockquote></details>

Done.
___
*[examples/R/server.c, line 63 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOz0Tq0CmHKmu1lIcF:-MlP3TPc7ARTIq1OAxIj:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Won't fit into the previous line?
</blockquote></details>

Done.
___
*[examples/R/server.c, line 90 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlP2i67BszwnTJhZDo6:-MlP3a1pCSy-BfdHLVxE:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`4 * KILOBYTE` :grin: 
</blockquote></details>

Done.
___
*[examples/R/server.c, line 99 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/25#-MlOzzcc47KBPy3AB3z0:-MlP3itU4zQWmS4VgGHO:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/8e5ca3aa8726996281545700158ae458baa17dc8/examples/R/server.c#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Simply `true` should be enough.

Ref: http://pmem.io/rpma/manpages/master/rpma_peer_cfg_set_direct_write_to_pmem.3
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25#-:-MlngZ_sAPXczvR_UpC8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/25#-:-MlnyLVU7HpMcF8nVS34:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
