### PR TITLE
example R: remove config_softroce.sh

### PR DESCRIPTION
**Pull request by ldorau**
Remove config_softroce.sh. SoftRoCE has to be configured on the host.
See: https://github.com/ldorau/2021-04-21.web/pull/3

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/15)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
@janekmi @osalyk please review

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/15#-:-MkgWble6UCfdMW94FTM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/15#-:-Mkgp_q32QdWFQrwYGqn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
