### PR TITLE
example R: is_pmem is always true

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[examples/R/server.c, line 198 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/39#-Mo3x3R-ABUdni0lcStA:-Mo3x3R-ABUdni0lcStB:bb9nolh) ([raw file](https://github.com/ldorau/2021-04-21/blob/fb1d00b8407d0e0773d1e79ae43d200e3aa43ed7/examples/R/server.c#L198)):*
> ```C
> 	if (is_pmem) {
> 		pmem_unmap(mr_ptr, mr_size);
> 		mr_ptr = NULL;
> ```

Is this unnecessary

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39#-:-Mo3zRxJC2E5f4tp8oMV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/R/server.c, line 198 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/39#-Mo3x3R-ABUdni0lcStA:-Mo3z36878YCujCj0ARZ:bdcnjkz) ([raw file](https://github.com/ldorau/2021-04-21/blob/fb1d00b8407d0e0773d1e79ae43d200e3aa43ed7/examples/R/server.c#L198)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Is this unnecessary
</blockquote></details>

@osalyk A question or a statement? ;-)

I'm ok with doing both these changes in a single PR. They are more or less related.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[examples/R/server.c, line 198 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/39#-Mo3x3R-ABUdni0lcStA:-Mo4-6OFBL8t69-HO16M:b-a8mbfo) ([raw file](https://github.com/ldorau/2021-04-21/blob/fb1d00b8407d0e0773d1e79ae43d200e3aa43ed7/examples/R/server.c#L198)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@osalyk A question or a statement? ;-)

I'm ok with doing both these changes in a single PR. They are more or less related.
</blockquote></details>

@osalyk The memory mapped at the line #54 has to be unmapped at the end.

I have renamed the label.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[examples/R/server.c, line 198 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/39#-Mo3x3R-ABUdni0lcStA:-Mo40Bx89d01cCW7dcdi:bc5936d) ([raw file](https://github.com/ldorau/2021-04-21/blob/fb1d00b8407d0e0773d1e79ae43d200e3aa43ed7/examples/R/server.c#L198)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk The memory mapped at the line #54 has to be unmapped at the end.

I have renamed the label.
</blockquote></details>

It was meant to be a question.
I was referring to: mr_ptr = NULL;

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[examples/R/server.c, line 198 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/39#-Mo3x3R-ABUdni0lcStA:-Mo413Wz3jxdC6BjO48r:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/fb1d00b8407d0e0773d1e79ae43d200e3aa43ed7/examples/R/server.c#L198)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

It was meant to be a question.
I was referring to: mr_ptr = NULL;

</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39#-:-Mo41RZ07LAtYvguhGEo:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/server.c, line 198 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/39#-Mo3x3R-ABUdni0lcStA:-Mo480NmCPe_HLIsTdkn:b-ftang7) ([raw file](https://github.com/ldorau/2021-04-21/blob/fb1d00b8407d0e0773d1e79ae43d200e3aa43ed7/examples/R/server.c#L198)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@osalyk `mr_ptr == NULL` was an easy fallback in case the source of the memory is not PMem.
Which is not needed anymore. :grin: 
___
*[examples/R/server.c, line 195 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/39#-Mo48Pc00DSoAtkmFJ4q:-Mo48Pc00DSoAtkmFJ4r:b-9n4ury) ([raw file](https://github.com/ldorau/2021-04-21/blob/a3cfd122ee1c6a77f2fa02773da279f593585988/examples/R/server.c#L195)):*
> ```C
> 
> err_unmap:
> 	pmem_unmap(mr_ptr, mr_size);
> ```

It seems we are consciously ignoring the return value. Please add `(void) ` at the begining.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/R/server.c, line 195 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/39#-Mo48Pc00DSoAtkmFJ4q:-Mo4AzIY3WQ3qYfXVuqm:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/a3cfd122ee1c6a77f2fa02773da279f593585988/examples/R/server.c#L195)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems we are consciously ignoring the return value. Please add `(void) ` at the begining.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:+1: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/39#-:-Mo4D37kAXCvwYJ93sOW:b-8fx2u7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
