### PR TITLE
example R: replace connection.h with common.h

### PR DESCRIPTION
**Pull request by osalyk**
- [x] update 2021-04-21.web - https://github.com/ldorau/2021-04-21.web/pull/28

This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3p5Il3O68PLKemYJV:-Mo3p5ImBwC_b9IYSxzR:b-vf2v2i) (no related file):*
@osalyk Please rebase

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3p5Il3O68PLKemYJV:-Mo3pWpMAH4xD_zSUHTc:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk Please rebase
</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3poAkDyKEQD-d6n63:-Mo3poAkDyKEQD-d6n64:b-5u33mz) (no related file):*
This PR can be merged when update of 2021-04-21.web is ready to be merged too.

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36#-:-Mo3pyNu5wYfkSASHTOJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by janekmi — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3we5R1godRI4JzvB9:-Mo3we5R1godRI4JzvBA:b-69pkez) (no related file):*
@osa have you confirmed all of these build properly?

---
___
*[examples/R/common.h, line 5 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3vnhj0W6GMxNLgl5R:-Mo3vnhk7wtTYEIr6Cvo:bv79snj) ([raw file](https://github.com/ldorau/2021-04-21/blob/b2754651ce236b53e7e06c1ddc72bb8f263e5d5d/examples/R/common.h#L5)):*
> ```objc
> 
> /*
>  * common.h -- a common functions declarations for example R
> ```

~~a~~ common
___
*[examples/R/common.h, line 5 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3w-U7AlzGp6cl6Y1E:-Mo3w-U7AlzGp6cl6Y1F:b-s2y7oq) ([raw file](https://github.com/ldorau/2021-04-21/blob/b2754651ce236b53e7e06c1ddc72bb8f263e5d5d/examples/R/common.h#L5)):*
> ```objc
> 
> /*
>  * common.h -- a common functions declarations for example R
> ```

the example
___
*[examples/R/common.c, line 5 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3wEZiEYOwoNKxRa2B:-Mo3wEZiEYOwoNKxRa2C:b2ngvbr) ([raw file](https://github.com/ldorau/2021-04-21/blob/b2754651ce236b53e7e06c1ddc72bb8f263e5d5d/examples/R/common.c#L5)):*
> ```C
> 
> /*
>  * common.c -- a common functions used by example R
> ```

. .

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @osa)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3poAkDyKEQD-d6n63:-Mo3xrJ4AdnGc1rqNjA1:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This PR can be merged when update of 2021-04-21.web is ready to be merged too.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3we5R1godRI4JzvB9:-Mo4-NJMC6GB1PCoF1jd:b2nign6) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@osa have you confirmed all of these build properly?
</blockquote></details>

yes

---
___
*[examples/R/common.h, line 5 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3vnhj0W6GMxNLgl5R:-Mo3xees3F58gyE7theY:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/b2754651ce236b53e7e06c1ddc72bb8f263e5d5d/examples/R/common.h#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~a~~ common
</blockquote></details>

Done.
___
*[examples/R/common.h, line 5 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3w-U7AlzGp6cl6Y1E:-Mo3xgULEG7_pw37BnXw:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/b2754651ce236b53e7e06c1ddc72bb8f263e5d5d/examples/R/common.h#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the example
</blockquote></details>

Done.
___
*[examples/R/common.c, line 5 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3wEZiEYOwoNKxRa2B:-Mo3xmUp3awgAbTyIfV0:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/b2754651ce236b53e7e06c1ddc72bb8f263e5d5d/examples/R/common.c#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

. .
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @osa)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi, @ldorau, @osa, and @osalyk)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo41sxz38LokMY7Ypeu:-Mo41sy-AWPgZUJhoSsO:b-3m29rj) (no related file):*
Please fix the date of this commit (Thu Aug 13 00:48:28 2020 -0400)

---

**Comment by osa** [comment]
Thanks for involving me in this repo. Sadly I think that was a mistake.  You wanted `osalyk` and not `osa`. I have not worked in `C` in almost 20 years. lol

**Review by ldorau — COMMENTED** [review]
Thanks @osa ! :-) It is never too late to try again ... ;-)

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36#-:-Mo44StbCgqPtgF5_LBQ:bpuhf0a)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi, @osa, and @osalyk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi, @osa, and @osalyk)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3we5R1godRI4JzvB9:-Mo44i-c2z2XLMa5GM3z:bg3xq5d) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Yes, they do.

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @osa)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo3we5R1godRI4JzvB9:-Mo45RyD9THw_frHdXgD:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, they do.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo41sxz38LokMY7Ypeu:-Mo45Smi3YIHitkT54mS:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please fix the date of this commit (Thu Aug 13 00:48:28 2020 -0400)
</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi, @osa, and @osalyk)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo41sxz38LokMY7Ypeu:-Mo45vQDBJh5TiY92g7M:bxbfaje) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, see below

---
___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo45u5yENFzElzjrWas):*
> ```
> on 8/13/2020 at 8:33 AM
> ```

????

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36#-:-Mo47p2n7Jjsz-s7wN1r:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo41sxz38LokMY7Ypeu:-Mo49qNJ031x_J5gKycF:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, see below
</blockquote></details>

Done.

---
___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo45u5yENFzElzjrWas):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> on 8/13/2020 at 8:33 AM
> ```

????
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/36#-:-Mo4A4id6e0aoaHVYJvK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[-- commits, line 1 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/36#-Mo45u5yENFzElzjrWas):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It is bug in Reviewable. Th date is OK on GitHub.

**Pull request merged**
