### PR TITLE
example R: add prefixes, fix messages and add new ones

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/44)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/44)* status: all files reviewed, 10 unresolved discussions (waiting on @ldorau)

___
*[examples/R/client.c, line 150 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9Enwj8KaWGzS8cL55:-Mo9Enwk073T6yf9VoPZ:b-1mm4lf) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L150)):*
> ```
> Client:
> ```
Client: error:
___
*[examples/R/client.c, line 175 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9EzgDAZPFe0AnB1AQ:-Mo9EzgDAZPFe0AnB1AR:b3g6vdo) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L175)):*
> ```
> Client: 
> ```
.
___
*[examples/R/client.c, line 182 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9F0LOBHCBYL1akeNB:-Mo9F0LOBHCBYL1akeNC:b3g6vdo) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L182)):*
> ```
> Client: 
> ```
.
___
*[examples/R/client.c, line 199 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9F6N3BO8gCEXDibk2:-Mo9F6N3BO8gCEXDibk3:b-u4dqk) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L199)):*
> ```
> Client:
> ```
.
___
*[examples/R/client.c, line 210 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9F9X77GjZKtlN4Do9:-Mo9F9X77GjZKtlN4DoA:b-u4dqk) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L210)):*
> ```
> Client:
> ```
.
___
*[examples/R/client.c, line 227 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FI0H2vta-sACePkW:-Mo9FI0H2vta-sACePkX:b3g6vdo) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L227)):*
> ```
> Client: 
> ```
.
___
*[examples/R/client.c, line 235 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FJyX3LmRIV_BWHAt:-Mo9FJyX3LmRIV_BWHAu:b3g6vdo) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L235)):*
> ```
> Client: 
> ```
.
___
*[examples/R/server.c, line 55 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FN6f9tvFm3Mnu96B:-Mo9FN6f9tvFm3Mnu96C:b2i266s) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/server.c#L55)):*
> ```
> Server: 
> ```
.
___
*[examples/R/server.c, line 61 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FOea6i8lpNitEHxI:-Mo9FOea6i8lpNitEHxJ:b2i266s) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/server.c#L61)):*
> ```
> Server: 
> ```
.
___
*[examples/R/server.c, line 68 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FQ0465VVRrHyrIKZ:-Mo9FQ0465VVRrHyrIK_:b2i266s) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/server.c#L68)):*
> ```
> Server: 
> ```
.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/44)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @grom72)

___
*[examples/R/client.c, line 150 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9Enwj8KaWGzS8cL55:-Mo9InaB9Xk3GGn5r7Pt:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L150)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Client:
> ```
Client: error:
</blockquote></details>

Done.
___
*[examples/R/client.c, line 175 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9EzgDAZPFe0AnB1AQ:-Mo9Ipi87x0_Dk65dhth:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L175)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Client: 
> ```
.
</blockquote></details>

Done.
___
*[examples/R/client.c, line 182 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9F0LOBHCBYL1akeNB:-Mo9IqPL4mBqM3t3YvXZ:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L182)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Client: 
> ```
.
</blockquote></details>

Done.
___
*[examples/R/client.c, line 199 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9F6N3BO8gCEXDibk2:-Mo9IrAm4HxoR0QgFh-n:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L199)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Client:
> ```
.
</blockquote></details>

Done.
___
*[examples/R/client.c, line 210 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9F9X77GjZKtlN4Do9:-Mo9Irt54SnCi-v9w4Ub:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L210)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Client:
> ```
.
</blockquote></details>

Done.
___
*[examples/R/client.c, line 227 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FI0H2vta-sACePkW:-Mo9IsWX1nx9Rc03TfNJ:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L227)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Client: 
> ```
.
</blockquote></details>

Done.
___
*[examples/R/client.c, line 235 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FJyX3LmRIV_BWHAt:-Mo9ItAI15btJVNgpVyC:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/client.c#L235)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Client: 
> ```
.
</blockquote></details>

Done.
___
*[examples/R/server.c, line 55 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FN6f9tvFm3Mnu96B:-Mo9Iu5b-PnQpNqMYDAn:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/server.c#L55)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Server: 
> ```
.
</blockquote></details>

Done.
___
*[examples/R/server.c, line 61 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FOea6i8lpNitEHxI:-Mo9Iui39dXnne9r9XNc:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/server.c#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Server: 
> ```
.
</blockquote></details>

Done.
___
*[examples/R/server.c, line 68 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/44#-Mo9FQ0465VVRrHyrIKZ:-Mo9IvOC500JDj9sbwp0:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/46f9de235701baea888ae32d94dbb67f4cea46cf/examples/R/server.c#L68)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Server: 
> ```
.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/44#-:-Mo9KmyJ6jCvzsBWIXGI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/44#-:-Mo9PNOhCb00SOh1Uvvn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/44#-:-MoI3jacCUHHk3UM3TKu:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
