### PR TITLE
example R: each user requires a dedicated port number

### PR DESCRIPTION
**Pull request by ldorau**
It requires: https://github.com/ldorau/2021-04-21.web/pull/7

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21#-:-MkpfnJc0R0h78kIRk4m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/run_main.sh, line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/21#-MlFEQTf0t06VLvzm5SZ:-MlFEQTf0t06VLvzm5S_:b-7nluo5) ([raw file](https://github.com/ldorau/2021-04-21/blob/b43f15eda6035c89d0634bc243f7f8cf9e946a4c/examples/R/run_main.sh#L7)):*
> ```Shell
> 
> SERVER_IP=$RPMA_SOFT_ROCE_IP
> SERVER_PORT=$((7200 + $PMEMUSER_ID))
> ```

Can you elaborate what is the additional value of having here an expression instead of a simple:

```sh
SERVER_PORT=$PMEMUSER_PORT
```

? Or even using `$PMEMUSER_PORT` directly?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/R/run_main.sh, line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/21#-MlFEQTf0t06VLvzm5SZ:-MlFF_1L4GcuIRa91aBb:b-kh4n0s) ([raw file](https://github.com/ldorau/2021-04-21/blob/b43f15eda6035c89d0634bc243f7f8cf9e946a4c/examples/R/run_main.sh#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can you elaborate what is the additional value of having here an expression instead of a simple:

```sh
SERVER_PORT=$PMEMUSER_PORT
```

? Or even using `$PMEMUSER_PORT` directly?
</blockquote></details>

1) Knowing `PMEMUSER_ID` we can use it in another place for something different too.
2) This the place where the port is used, so IMHO it should be calculated here.

**Review by janekmi — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21#-:-MlFvzUxB17jWlogJFx5:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[examples/R/run_main.sh, line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/21#-MlFEQTf0t06VLvzm5SZ:-MlFv4HQ7ZmjMNBDXX_K:b-82k6z7) ([raw file](https://github.com/ldorau/2021-04-21/blob/b43f15eda6035c89d0634bc243f7f8cf9e946a4c/examples/R/run_main.sh#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) Knowing `PMEMUSER_ID` we can use it in another place for something different too.
2) This the place where the port is used, so IMHO it should be calculated here.
</blockquote></details>

1. I got the idea but I'm not sure it will be needed. I'm just afraid nobody will have the interest to clean it up in case it turns out it is not needed and the solution is overly complicated.
2. The port is the same here and in the neighbouring script. I don't like having duplicates. That's it.

I will leave the decision to our last resort. @grom72, what is your stand on this topic? ;-)
I'm fine with the existing solution. I'm just not a fan of it.

**Review by ldorau — COMMENTED** [review]
Using ports > 62000, see:
https://en.wikipedia.org/wiki/Ephemeral_port
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21#-:-MlKED_C0uGU6QonPUNo:b-ukov7s)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @grom72, @janekmi, and @osalyk)

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/21#-MlKGUVDBI3tos9XdyKV:-MlFw0LTBT_8IE9OK2iY:bsmw4ro) (no related file):*
@ldorau can you elaborate a little bit on why you have picked 62000+?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/21#-MlKGUVDBI3tos9XdyKV:-MlKHARK6YOgkvxFruM1:bpv6fqr) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@ldorau can you elaborate a little bit on why you have picked 62000+?
</blockquote></details>

See: https://github.com/ldorau/2021-04-21/pull/21#pullrequestreview-772507132

According to the links above ("*Many Linux kernels use the port range 32768–60999.*") the range > 61000 is most probably to be not used.

---

**Review by janekmi — COMMENTED** [review]
:goat:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21#-:-MlKIe-z4nTgitAXRZc_:bnd2vnu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/21#-:-MlKPKRn6-6huIGcSC2a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
