### PR TITLE
example R: verify direct write to PMEM support

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/40)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/40#-:-Mo40krl44nlWqMPxvgK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/40)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/client.c, line 133 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/40#-Mo48l7a8vAyxzwQ_0Vn:-Mo48l7a8vAyxzwQ_0Vo:b-8n45xo) ([raw file](https://github.com/ldorau/2021-04-21/blob/fd443aba3250918e3214a26331b60a9d2a4b1db9/examples/R/client.c#L133)):*
> ```C
> 	if (!direct_write_to_pmem) {
> 		(void) fprintf(stderr,
> 			"Error: the server does not support direct write to PMEM\n");
> ```

Direct Write to PMem

Ref: https://pmem.io/rpma/documentation/basic-direct-write-to-pmem.html

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/40)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[examples/R/client.c, line 133 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/40#-Mo48l7a8vAyxzwQ_0Vn:-Mo4BUhm0nu_Ym-3ZaMG:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/fd443aba3250918e3214a26331b60a9d2a4b1db9/examples/R/client.c#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Direct Write to PMem

Ref: https://pmem.io/rpma/documentation/basic-direct-write-to-pmem.html
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/40)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/40#-:-Mo4DCda5yXNyi6ZD4X-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
