### PR TITLE
Remove using libpmem from the client

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/2)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/2)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/R/client.c, line 86 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/2#-MkHbKop7mUgdJ_BiJka:-MkHbKop7mUgdJ_BiJkb:b3kre) ([raw file](https://github.com/ldorau/2021-04-21/blob/08f136ce339c2355b17a283313efca176c774113/examples/R/client.c#L86)):*
> ```C
> 	struct hello_t *hello = NULL;
> 
> 	/* if no pmem support or it is not provided */
> ```

?
___
*[examples/R/client.c, line 242 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/2#-MkHbOYYA6h1Ifq-fdNP:-MkHbOYYA6h1Ifq-fdNQ:b-qyuobm) ([raw file](https://github.com/ldorau/2021-04-21/blob/08f136ce339c2355b17a283313efca176c774113/examples/R/client.c#L242)):*
> ```C
> 
> err_free:
> 	if (mr_ptr != NULL)
> ```

It seems obvious.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/2)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[examples/R/client.c, line 86 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/2#-MkHbKop7mUgdJ_BiJka:-MkHcdgHDTEtyQmFUY__:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/08f136ce339c2355b17a283313efca176c774113/examples/R/client.c#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[examples/R/client.c, line 242 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/2#-MkHbOYYA6h1Ifq-fdNP:-MkHcc574ihQQdii5f4T:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/08f136ce339c2355b17a283313efca176c774113/examples/R/client.c#L242)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems obvious.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/2#-:-MkHjM10DtWS5A-dE93f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/2#-:-MkI1aUQ8zTsgIQ7NDXM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/2#-:-MkLiF9D595_SnV6RfE6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
