### PR TITLE
server: set and print the initial content

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [ ] #3

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/4)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/4)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/server.c, line 127 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/4#-MkLsAvsDMv2upU0a9EP:-MkLsAvsDMv2upU0a9EQ:b-8fnwnq) ([raw file](https://github.com/ldorau/2021-04-21/blob/85cf5e138c629500e941516b6b62347ce96aca5b/examples/R/server.c#L127)):*
> ```C
> 	/* set and print the initial content */
> 	char *data_ptr = (char *)mr_ptr + data_offset;
> 	strcpy(data_ptr, INIT_STR);
> ```

You can use `strncpy()` which is easier acceptable by static analyzer. (KILOBYTE)

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/4)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/4)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/R/server.c, line 127 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/4#-MkLsAvsDMv2upU0a9EP:-MkLwEKv0w3Qw-m2XVIH:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/85cf5e138c629500e941516b6b62347ce96aca5b/examples/R/server.c#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can use `strncpy()` which is easier acceptable by static analyzer. (KILOBYTE)
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/4#-:-MkLw_DRDTQoii3wx6hF:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/4#-:-MkLxWxPDJbkbAiXP5bT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
