### PR TITLE
example R: make the main example build and run

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/18)

### CODE REVIEW

**Comment by ldorau** [comment]
@janekmi @osalyk @grom72 please review

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/18)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[examples/R/build_xxx.sh, line 3 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI5Qn441CD0107j_T:-MklI5Qn441CD0107j_U:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/build_xxx.sh#L3)):*
> ```Shell
> #!/bin/bash -ex
> #
> # XXX placeholder
> ```

.
___
*[examples/R/build_xxx.sh, line 9 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklIC58Dl7-SI-zfp8e:-MklIC58Dl7-SI-zfp8f:bebn17b) ([raw file](https://github.com/ldorau/2021-04-21/blob/a7b0e828b4e691ad2d03a4c45a171ac4ef7e2d9b/examples/R/build_xxx.sh#L9)):*
> ```Shell
> cd build
> cmake ..
> make xxx
> ```

This way you build all targets e.g. simple_* examples. Can we narrow it down?
___
*[examples/R/run_xxx.sh, line 3 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI8JM-PCTy3vUTBIE:-MklI8JM-PCTy3vUTBIF:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/run_xxx.sh#L3)):*
> ```Shell
> #!/bin/bash -ex
> #
> # XXX placeholder
> ```

.
___
*[examples/R/run_xxx.sh, line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI9vvC7rX2P9iIVWk:-MklI9vvC7rX2P9iIVWl:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/run_xxx.sh#L7)):*
> ```Shell
> 
> SERVER_IP=$RPMA_SOFT_ROCE_IP
> SERVER_PORT=7204
> ```

.
___
*[examples/R/run_xxx.sh, line 10 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI987A657RG1ADGHV:-MklI987A657RG1ADGHW:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/run_xxx.sh#L10)):*
> ```Shell
> 
> cd build
> ./server $SERVER_IP $SERVER_PORT & # XXX
> ```

.
___
*[examples/R/run_xxx.sh, line 11 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI8td4GaMPhPq4LXJ:-MklI8td4GaMPhPq4LXK:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/run_xxx.sh#L11)):*
> ```Shell
> cd build
> ./server $SERVER_IP $SERVER_PORT & # XXX
> ./client $SERVER_IP $SERVER_PORT   # XXX
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/18)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[examples/R/build_xxx.sh, line 3 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI5Qn441CD0107j_T:-MklK4Tq2-TztZSTfw6h:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/build_xxx.sh#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/R/build_xxx.sh, line 9 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklIC58Dl7-SI-zfp8e:-MklK4wP4ttcZGwsoWUP:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/a7b0e828b4e691ad2d03a4c45a171ac4ef7e2d9b/examples/R/build_xxx.sh#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This way you build all targets e.g. simple_* examples. Can we narrow it down?
</blockquote></details>

Done.
___
*[examples/R/run_xxx.sh, line 3 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI8JM-PCTy3vUTBIE:-MklK5sa98jsJkuXH4Du:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/run_xxx.sh#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/R/run_xxx.sh, line 7 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI9vvC7rX2P9iIVWk:-MklKL239IMklL3Rnbck:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/run_xxx.sh#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/R/run_xxx.sh, line 10 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI987A657RG1ADGHV:-MklKLVM7R7d6LuQx4tq:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/run_xxx.sh#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/R/run_xxx.sh, line 11 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/18#-MklI8td4GaMPhPq4LXJ:-MklKLyOAFtHBUC9jGzN:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/710256c21cf0ac7ea0e6a9e2741d640375e25268/examples/R/run_xxx.sh#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/18#-:-MklL9EaCzYtf6y4Cen9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/18#-:-MklQlRf7bSkVqHeD8xT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
