### PR TITLE
example R: flush stdout in server

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/43)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/43#-:-Mo9OvRV34ptOaVcEfYW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/43)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/server.c, line 89 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/43#-Mo9pJOGBaxdJWmkB5Lq:-Mo9pJOH-778Q2XiGW1C:b-gf8j3s) ([raw file](https://github.com/ldorau/2021-04-21/blob/a8129e475d194ce6be079c81fc66c1aad1a8074b/examples/R/server.c#L89)):*
Please give a line of comment. In a year you will forget what it is all about. ;-)
e.g.

> Flush the output buffer in order to assure the initial value will be really close to the top of the console in the case of mixing the client and the server output.

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/43#-:-MoI3Y6D8arR0GtuXix6:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/43)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[examples/R/server.c, line 89 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/43#-Mo9pJOGBaxdJWmkB5Lq:-MoXe_43BYPp6r5Lxodq:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/a8129e475d194ce6be079c81fc66c1aad1a8074b/examples/R/server.c#L89)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please give a line of comment. In a year you will forget what it is all about. ;-)
e.g.

> Flush the output buffer in order to assure the initial value will be really close to the top of the console in the case of mixing the client and the server output.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/43#-:-MoY9_oG4YlWyf9e-jmk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
