### PR TITLE
client: remove translating messages

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #5 
- [x] #6
- [x] #9

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/10)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/10)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/client.c, line 37 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/10#-MkLxvnj2tEUN0r4ZORq:-MkLxvnj2tEUN0r4ZORr:b-1uvu3w) ([raw file](https://github.com/ldorau/2021-04-21/blob/f2e188330bce5f8be77c72ed1013867f8157781b/examples/R/client.c#L37)):*
> ```C
> 	strncpy(hello->str, hello_str, HELLO_STR_SIZE - 1);
> 	hello->str[HELLO_STR_SIZE - 1] = '\0';
> }
> ```

In this case, having a function for this is a little bit of an overkill. ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/10)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/R/client.c, line 37 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/10#-MkLxvnj2tEUN0r4ZORq:-MkMAj4E9hZGpO45-HHJ:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/f2e188330bce5f8be77c72ed1013867f8157781b/examples/R/client.c#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In this case, having a function for this is a little bit of an overkill. ;-)
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/10#-:-MkMGk9W51mtrdrO_bja:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/10#-:-MkMR095-5SLyE3xf7gy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi and @osalyk)

**Pull request merged**
