### PR TITLE
client: add reading the initial server's content

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #5 
- [x] #6

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/9)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/9)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[examples/R/client.c, line 159 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/9#-MkLwNYd8L3A09WcTwxp:-MkLwNYe5NPLj2Gx3t8I:b-dsq5sr) ([raw file](https://github.com/ldorau/2021-04-21/blob/2f69f0f5b51adf8fa3a998dd86b9f15649491b27/examples/R/client.c#L159)):*
> ```C
> 
> 	/* read the initial value */
> 	ret = rpma_read(conn, local_mr, 0, remote_mr, 0, remote_size,
> ```

0 -> local_offset + offsetof(struct hello_t, str)
0 -> remote_offset
___
*[examples/R/client.c, line 188 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/9#-MkLx1Pt81AGG_nGeoUx:-MkLx1Pt81AGG_nGeoUy:b-yxh3qo) ([raw file](https://github.com/ldorau/2021-04-21/blob/2f69f0f5b51adf8fa3a998dd86b9f15649491b27/examples/R/client.c#L188)):*
> ```C
> 	}
> 
> 	(void) fprintf(stdout, "Read the initial content of the server memory: %s\n", (char *)local_mr_ptr);
> ```

The initial read content...?
___
*[examples/R/client.c, line 193 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/9#-MkLx9as0UGv6Xpa58HZ:-MkLx9as0UGv6Xpa58H_:brou73e) ([raw file](https://github.com/ldorau/2021-04-21/blob/2f69f0f5b51adf8fa3a998dd86b9f15649491b27/examples/R/client.c#L193)):*
> ```C
> 	struct hello_t *hello = local_mr_ptr;
> 	write_hello_str(hello, en);
> 	(void) printf("Sending (rpma_write()) the message: %s\n", hello->str);
> ```

`Writing`? :D

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/9)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[examples/R/client.c, line 159 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/9#-MkLwNYd8L3A09WcTwxp:-MkM7TzQ4YxInXrAixvu:b-uqed4h) ([raw file](https://github.com/ldorau/2021-04-21/blob/2f69f0f5b51adf8fa3a998dd86b9f15649491b27/examples/R/client.c#L159)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

0 -> local_offset + offsetof(struct hello_t, str)
0 -> remote_offset
</blockquote></details>

OK: 0 -> local_offset (already is == 0)
OK: 0 -> remote_offset (already is == 0)

offsetof(struct hello_t, str) - NO (it will be used later as a `struct hello_t`)
___
*[examples/R/client.c, line 188 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/9#-MkLx1Pt81AGG_nGeoUx:-MkM8PAr5Of-Zvj4WEU3:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/2f69f0f5b51adf8fa3a998dd86b9f15649491b27/examples/R/client.c#L188)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The initial read content...?
</blockquote></details>

Done.
___
*[examples/R/client.c, line 193 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/9#-MkLx9as0UGv6Xpa58HZ:-MkM8PVz8qQ3r-chLrR-:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/2f69f0f5b51adf8fa3a998dd86b9f15649491b27/examples/R/client.c#L193)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`Writing`? :D
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[examples/R/client.c, line 159 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/9#-MkLwNYd8L3A09WcTwxp:-MkMAwT24PpnbQYYcMy-:b-cv64s9) ([raw file](https://github.com/ldorau/2021-04-21/blob/2f69f0f5b51adf8fa3a998dd86b9f15649491b27/examples/R/client.c#L159)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK: 0 -> local_offset (already is == 0)
OK: 0 -> remote_offset (already is == 0)

offsetof(struct hello_t, str) - NO (it will be used later as a `struct hello_t`)

</blockquote></details>

It may be the case, that after removing the language from the `struct hello_t` the whole structure does not make much sense.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/9#-:-MkMCX337wRStxd-9hhM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[examples/R/client.c, line 159 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/9#-MkLwNYd8L3A09WcTwxp:-MkMCmzr1tecXbJ5x9JK:b-jo43uy) ([raw file](https://github.com/ldorau/2021-04-21/blob/2f69f0f5b51adf8fa3a998dd86b9f15649491b27/examples/R/client.c#L159)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It may be the case, that after removing the language from the `struct hello_t` the whole structure does not make much sense.
</blockquote></details>

Yes, exactly

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/9#-:-MkMCbLz6i5pg_2adDbh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[examples/R/client.c, line 159 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/9#-MkLwNYd8L3A09WcTwxp:-MkMF6z6DxmsdS-IimtT:b-ixu8uq) ([raw file](https://github.com/ldorau/2021-04-21/blob/2f69f0f5b51adf8fa3a998dd86b9f15649491b27/examples/R/client.c#L159)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, exactly
</blockquote></details>

@janekmi removed: https://github.com/ldorau/2021-04-21/pull/12

**Pull request merged**
