### PR TITLE
client: rename variables from src_/dst_ to local_/remote_

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #2

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/5)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/5)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/R/client.c, line 77 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/5#-MkLu3ZH1Nb6znQRDT8L:-MkLu3ZI0_CwG9w8vA1w:bvijivn) ([raw file](https://github.com/ldorau/2021-04-21/blob/54d82337c3025349a2f12e1b655058d4a4b1d467/examples/R/client.c#L77)):*
> ```C
> 	void *local_mr_ptr;
> 	size_t local_mr_size = 0;
> 	size_t data_offset = 0;
> ```

local_offset?
___
*[examples/R/client.c, line 93 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/5#-MkLtRrP8EeC0jUK0k_D:-MkLtRrP8EeC0jUK0k_E:bdmirpy) ([raw file](https://github.com/ldorau/2021-04-21/blob/54d82337c3025349a2f12e1b655058d4a4b1d467/examples/R/client.c#L93)):*
> ```C
> 	hello = local_mr_ptr;
> 
> 	/* write an initial value */
> ```

Considering other changes we will have "initial" values on both ends now.
Maybe `write (the next) value` is less confusing?

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/5)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/5)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[examples/R/client.c, line 77 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/5#-MkLu3ZH1Nb6znQRDT8L:-MkLxFpL5SLXo3rBjLnk:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/54d82337c3025349a2f12e1b655058d4a4b1d467/examples/R/client.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

local_offset?
</blockquote></details>

Done.
___
*[examples/R/client.c, line 93 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/5#-MkLtRrP8EeC0jUK0k_D:-MkLyLz-1dWVosXUxfAP:b-v68qqo) ([raw file](https://github.com/ldorau/2021-04-21/blob/54d82337c3025349a2f12e1b655058d4a4b1d467/examples/R/client.c#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Considering other changes we will have "initial" values on both ends now.
Maybe `write (the next) value` is less confusing?
</blockquote></details>

It is out of scope of this PR. It will be changed later, see:
https://github.com/ldorau/2021-04-21/blob/Adjust-the-librpma-example-R/examples/R/client.c#L173
(in https://github.com/ldorau/2021-04-21/pull/8)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/5)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/client.c, line 77 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/5#-MkLu3ZH1Nb6znQRDT8L:-MkLzWBCAB1G9S7p87Tr:b-83og3x) ([raw file](https://github.com/ldorau/2021-04-21/blob/54d82337c3025349a2f12e1b655058d4a4b1d467/examples/R/client.c#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/5)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/R/client.c, line 77 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/5#-MkLu3ZH1Nb6znQRDT8L:-MkM1Q4K-fDryn1tNSwE:bvd1r8j) ([raw file](https://github.com/ldorau/2021-04-21/blob/54d82337c3025349a2f12e1b655058d4a4b1d467/examples/R/client.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nope.
</blockquote></details>

Forgot to push the changes ...

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/5#-:-MkM204v5aDnnaj_drEV:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/5#-:-MkM23Bi47z3r1HHkcI0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
