### PR TITLE
common: change messages

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #5 
- [x] #6 
- [x] #9 
- [x] #3 
- [x] #4 

:-DDD

---
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/11)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/11)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[examples/R/client.c, line 26 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/11#-MkMGzPO8ANWZqf523hI:-MkMGzPPD7E06aOpdwOc:bgkpmd9) ([raw file](https://github.com/ldorau/2021-04-21/blob/110e5f70b3ae3e7d766d42c79a6c45d24b2fc7ce/examples/R/client.c#L26)):*
> ```C
> };
> 
> static const char *hello_str = "This is the message sent by the client to the server.";
> ```

I liked the Hello World reference...

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/11)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[examples/R/client.c, line 26 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/11#-MkMGzPO8ANWZqf523hI:-MkMJCMN2TKop9Q-iPu7:bwvyox4) ([raw file](https://github.com/ldorau/2021-04-21/blob/110e5f70b3ae3e7d766d42c79a6c45d24b2fc7ce/examples/R/client.c#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I liked the Hello World reference...
</blockquote></details>

Reverted

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/11)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/11#-MkMNFov7K2UJjfh0XP8:-MkMNFowD6AyHSzzL7LO:b-ubuelf) (no related file):*
So, what is this PR all about now? ;-)

---

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/11#-:-MkMRHU86oFWIU8J89KE:bnfp4nl)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/11)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/11#-MkMNFov7K2UJjfh0XP8:-MkMYoxU6mt8k5eOUGam:bhaju3o) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So, what is this PR all about now? ;-)
</blockquote></details>

See changes in server.c

---

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/11#-:-MkM_NeC30Ny4hA7_C7h:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
