### PR TITLE
example R: add scripts and *.c files required for the story

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/R/run_test_ping.sh, line 6 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/13#-MkaxIls0rtP3BcJiJX1:-MkaxIls0rtP3BcJiJX2:buximnt) ([raw file](https://github.com/ldorau/2021-04-21/blob/00124bd16e7dcbb0167eb6e0e970e10521c466ed/examples/R/run_test_ping.sh#L6)):*
> ```Shell
> #
> 
> ping 192.168.100.1
> ```

```
SERVER_IP=192.168.1.100
ping -n5 $SERVER_IP
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[examples/R/build_simple.sh, line 6 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/13#-Mkcii_u0PgYLq6AOh7t:-Mkcii_u0PgYLq6AOh7u:b-p784c9) ([raw file](https://github.com/ldorau/2021-04-21/blob/00124bd16e7dcbb0167eb6e0e970e10521c466ed/examples/R/build_simple.sh#L6)):*
> ```Shell
> #
> 
> cd build
> ```

mkdir -p build
___
*[examples/R/build_xxx.sh, line 6 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/13#-MkciqGn4dkO7lHVftvR:-MkciqGn4dkO7lHVftvS:b-p784c9) ([raw file](https://github.com/ldorau/2021-04-21/blob/00124bd16e7dcbb0167eb6e0e970e10521c466ed/examples/R/build_xxx.sh#L6)):*
> ```Shell
> #
> 
> cd build
> ```

mkdir -p build

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/R/run_test_ping.sh, line 6 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/13#-MkaxIls0rtP3BcJiJX1:-MkcyuVd2r0yXBE7vvfT:b-twnh6s) ([raw file](https://github.com/ldorau/2021-04-21/blob/00124bd16e7dcbb0167eb6e0e970e10521c466ed/examples/R/run_test_ping.sh#L6)):*
> ping -n5 $SERVER_IP

ping -c5 $SERVER_IP

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[examples/R/build_simple.sh, line 6 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/13#-Mkcii_u0PgYLq6AOh7t:-MkcyCnO1rhf8mA1YFXO:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/00124bd16e7dcbb0167eb6e0e970e10521c466ed/examples/R/build_simple.sh#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

mkdir -p build
</blockquote></details>

Done.
___
*[examples/R/build_xxx.sh, line 6 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/13#-MkciqGn4dkO7lHVftvR:-MkcyIqDB6pvlg6R3vIf:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/00124bd16e7dcbb0167eb6e0e970e10521c466ed/examples/R/build_xxx.sh#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

mkdir -p build
</blockquote></details>

Done.
___
*[examples/R/run_test_ping.sh, line 6 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/13#-MkaxIls0rtP3BcJiJX1:-MkcyTq40zP_MzRzd8f_:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/00124bd16e7dcbb0167eb6e0e970e10521c466ed/examples/R/run_test_ping.sh#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
SERVER_IP=192.168.1.100
ping -n5 $SERVER_IP
```

</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/R/run_test_ping.sh, line 6 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/13#-MkaxIls0rtP3BcJiJX1:-Mkcz9Iz3xwLNsoyPazg:basm3u1) ([raw file](https://github.com/ldorau/2021-04-21/blob/00124bd16e7dcbb0167eb6e0e970e10521c466ed/examples/R/run_test_ping.sh#L6)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ping -c5 $SERVER_IP

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[examples/R/run_test_ping.sh, line 6 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/13#-MkaxIls0rtP3BcJiJX1:-MkczVk_6ic1sTcBmPMc:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/00124bd16e7dcbb0167eb6e0e970e10521c466ed/examples/R/run_test_ping.sh#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

ping -c5 $SERVER_IP
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13#-:-Mkd-VMZ4rsKlLxlZxbo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/13#-Mkewn8f9baTtCHJ6h5J:-Mkewn8f9baTtCHJ6h5K:b7hje3n) (no related file):*
what do you think about renaming simple_client/server -> connection_client/server and run_simple => run_connection
in such case we do not need any XXX for main files.
alternative option would be connection_setup_client/server

---

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13#-:-MkfXuTk3EzzctK8bvCz:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13#-:-MkfcIXg4PjsKC5PE_a6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/13#-Mkewn8f9baTtCHJ6h5J:-MkfsUmy3Y-twVuYsIat:b-ese0u6) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what do you think about renaming simple_client/server -> connection_client/server and run_simple => run_connection
in such case we do not need any XXX for main files.
alternative option would be connection_setup_client/server
</blockquote></details>

But having renamed `simple_` to `connection_` does not automatically rename `xxx_` to anything meaningful.
What is your proposition instead of `xxx_` placeholder?

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/2021-04-21/13#-Mkewn8f9baTtCHJ6h5J:-Mkg4msi5NXM9BeOKTrB:brht5f9) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

But having renamed `simple_` to `connection_` does not automatically rename `xxx_` to anything meaningful.
What is your proposition instead of `xxx_` placeholder?
</blockquote></details>

@ldorau We have agreed to rename these later on.

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/13)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
