### PR TITLE
example R: add simple example

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)

### CODE REVIEW

**Comment by ldorau** [comment]
@janekmi @osalyk @grom72 please review

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-MkkXXGb5aq1CB__Wu42:bcuj8ai) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
> ```
> Hello server!
> ```
It's me, client!
___
*[examples/R/simple_server.c, line 53 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXy156ya-UO8hS_gc:-MkkXy156ya-UO8hS_gd:bp8id3e) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_server.c#L53)):*
> ```
> Hello client!
> ```
It's me, server!

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[examples/R/simple_client.c, line 58 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkYt6DASPTuDD1wDA-:-MkkYt6DASPTuDD1wDA0:b8trb6b) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L58)):*
> ```
> "Received a message: %s\n"
> ```
"\nClient: Received a message: %s\n"
Server and client will run in the same console, so we have to distinguish every message.
Additionally, we need some mechanism to distinguish clearly this message from librpma logging messages.
___
*[examples/R/simple_server.c, line 65 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkYoiSD6VGNTn4GruC:-MkkYoiSD6VGNTn4GruD:b1eofmk) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_server.c#L65)):*
> ```
> "Received a message: %s\n"
> ```
.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-Mkk_4Q2-pFCP7DwP2L3:b7jk8o7) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Hello server!
> ```
It's me, client!
</blockquote></details>

"The client says hello to the server" ?
___
*[examples/R/simple_client.c, line 58 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkYt6DASPTuDD1wDA-:-Mkka2lq-8PwWqZl3Wof:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> "Received a message: %s\n"
> ```
"\nClient: Received a message: %s\n"
Server and client will run in the same console, so we have to distinguish every message.
Additionally, we need some mechanism to distinguish clearly this message from librpma logging messages.
</blockquote></details>

Done.
___
*[examples/R/simple_server.c, line 53 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXy156ya-UO8hS_gc:-Mkk_GJx-c70hKF7Ao9D:b-5tobop) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_server.c#L53)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Hello client!
> ```
It's me, server!
</blockquote></details>

"The server says hello to the client" ?
___
*[examples/R/simple_server.c, line 65 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkYoiSD6VGNTn4GruC:-Mkka1MQ3ymbOubdgENi:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_server.c#L65)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> "Received a message: %s\n"
> ```
.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-MkkcU0d6iQA4vAvdc6o:b32v57) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

"The client says hello to the server" ?
</blockquote></details>

+1

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-Mkkqjt57roLZv-Tq2jK:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[examples/R/build_simple.sh, line 3 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkoE3FAFwYDJq3GfRs:-MkkoE3FAFwYDJq3GfRt:bdvhzc3) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/build_simple.sh#L3)):*
> ```Shell
> #!/bin/bash -ex
> #
> # XXX placeholder
> ```

Following the repository convention:

```sh
# shell commands to build the simple_* example
```
___
*[examples/R/run_simple.sh, line 3 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkkpauv-uP5fvZREJgc:-Mkkpauv-uP5fvZREJgd:b-3vhbw3) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/run_simple.sh#L3)):*
> ```Shell
> #!/bin/bash -ex
> #
> # XXX placeholder
> ```

shell commands to run the simple_* example
___
*[examples/R/run_simple.sh, line 7 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkplbJE1sksZcjqpqF:-MkkplbJE1sksZcjqpqG:bekawlg) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/run_simple.sh#L7)):*
> ```Shell
> 
> SERVER_IP=$RPMA_SOFT_ROCE_IP
> SERVER_PORT=7204
> ```

`# XXX each user requires a dedicated port number`
___
*[examples/R/run_simple.sh, line 10 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl1jyN9Fe0cJGZUbk3:-Mkl1jyN9Fe0cJGZUbk4:b-ynra1c) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/run_simple.sh#L10)):*
> ```Shell
> 
> cd build
> ./simple_server $SERVER_IP $SERVER_PORT & # XXX
> ```

`# XXX PMem needed
___
*[examples/R/run_simple.sh, line 11 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl1g01CF7DBbZo2GPh:-Mkl1g01CF7DBbZo2GPi:braf0i1) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/run_simple.sh#L11)):*
> ```Shell
> cd build
> ./simple_server $SERVER_IP $SERVER_PORT & # XXX
> ./simple_client $SERVER_IP $SERVER_PORT   # XXX
> ```

Please remove the comment.
___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-Mkl2tu1BGcp-VVswGn7:b-2e3fb5) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Reminder:

```
/*
 * Limited by the maximum length of the private data
 * for rdma_connect() in case of RDMA_PS_TCP (28 bytes).
 */
```

Ref: https://github.com/pmem/fio/blob/rpma/engines/librpma_fio.h#L51
___
*[examples/R/simple_client.c, line 65 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl3D314htBVQTIT0Hi:-Mkl3D314htBVQTIT0Hj:b-dh0574) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/simple_client.c#L65)):*
> ```C
> 	/*
> 	 * Disconnect, wait for RPMA_CONN_CLOSED
> 	 * and delete the connection structure.
> ```

Won't it fit into a single line?

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[examples/R/simple_client.c, line 67 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl3ugE5asM3JqcqyWd:-Mkl3ugE5asM3JqcqyWe:blq5vek) ([raw file](https://github.com/ldorau/2021-04-21/blob/e4a7c4caf8f465290d0eea13f829f44fa9455c4b/examples/R/simple_client.c#L67)):*
> ```C
> 	 * and delete the connection structure.
> 	 */
> 	(void) common_disconnect_and_wait_for_conn_close(&conn);
> ```

`ret =` ?
___
*[examples/R/simple_server.c, line 53 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl3iODAU2ypVlGW7rF:-Mkl3iODAU2ypVlGW7rG:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21/blob/e4a7c4caf8f465290d0eea13f829f44fa9455c4b/examples/R/simple_server.c#L53)):*
> ```C
> 	 * establishment.
> 	 */
> 	const char *msg = "The server says hello to the client!";
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: 1 of 5 files reviewed, 9 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/R/build_simple.sh, line 3 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkoE3FAFwYDJq3GfRs:-MklAdUZAQ4MniGhZuXI:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/build_simple.sh#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Following the repository convention:

```sh
# shell commands to build the simple_* example
```
</blockquote></details>

Done.
___
*[examples/R/run_simple.sh, line 3 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkkpauv-uP5fvZREJgc:-MklAfl2EOK0uPuFu5nb:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/run_simple.sh#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

shell commands to run the simple_* example
</blockquote></details>

Done.
___
*[examples/R/run_simple.sh, line 7 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkplbJE1sksZcjqpqF:-MklAmRB1to3Il72_9mw:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/run_simple.sh#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`# XXX each user requires a dedicated port number`
</blockquote></details>

Done.
___
*[examples/R/run_simple.sh, line 10 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl1jyN9Fe0cJGZUbk3:-MklArTVA-yCM3RkSaco:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/run_simple.sh#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`# XXX PMem needed
</blockquote></details>

Done.
___
*[examples/R/run_simple.sh, line 11 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl1g01CF7DBbZo2GPh:-MklAtf47H5U_WNjuOBX:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/run_simple.sh#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove the comment.
</blockquote></details>

Done.
___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-MklDWR56oT3a9ASfI-z:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Reminder:

```
/*
 * Limited by the maximum length of the private data
 * for rdma_connect() in case of RDMA_PS_TCP (28 bytes).
 */
```

Ref: https://github.com/pmem/fio/blob/rpma/engines/librpma_fio.h#L51
</blockquote></details>

Done.
___
*[examples/R/simple_client.c, line 65 at r2](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl3D314htBVQTIT0Hi:-MklDjO46sNK6oH_INrD:bh8q0ik) ([raw file](https://github.com/ldorau/2021-04-21/blob/6ffe72d8676733629712fdd1555eda28f6f93c39/examples/R/simple_client.c#L65)):*
> 80 chars
___
*[examples/R/simple_client.c, line 67 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl3ugE5asM3JqcqyWd:-MklDpe4EAXOV2_cfQkS:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/e4a7c4caf8f465290d0eea13f829f44fa9455c4b/examples/R/simple_client.c#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`ret =` ?
</blockquote></details>

Done.
___
*[examples/R/simple_server.c, line 53 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl3iODAU2ypVlGW7rF:-MklDqzd3w90X6UkCBxe:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/e4a7c4caf8f465290d0eea13f829f44fa9455c4b/examples/R/simple_server.c#L53)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-MklG2037TgHSClKzasW:bexl7vc) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We are limited to 28 bytes. Your string now is 29 bytes including the NULL-terminator.
___
*[examples/R/simple_server.c, line 53 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl3iODAU2ypVlGW7rF:-MklGs8zBXbVxj6LbnN4:b3kqx) ([raw file](https://github.com/ldorau/2021-04-21/blob/e4a7c4caf8f465290d0eea13f829f44fa9455c4b/examples/R/simple_server.c#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-MklJ14DC3nFBNVlnqx0:b-2v4437) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We are limited to 28 bytes. Your string now is 29 bytes including the NULL-terminator.
</blockquote></details>

No, pdata.len == 28
___
*[examples/R/simple_server.c, line 53 at r3](https://reviewable.io/reviews/ldorau/2021-04-21/16#-Mkl3iODAU2ypVlGW7rF:-MklJ4NO-gcCuKQ6no66:b-2v4437) ([raw file](https://github.com/ldorau/2021-04-21/blob/e4a7c4caf8f465290d0eea13f829f44fa9455c4b/examples/R/simple_server.c#L53)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

No, pdata.len == 28

**Review by janekmi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16#-:-MklOEMoA2ddnji78hSL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-MklP-La-wYZvR3OhMlE:b-3p17t8) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, pdata.len == 28
</blockquote></details>

@janekmi ping

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-MklP54C9cHOqDqHo8gt:b-nanyuw) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi ping
</blockquote></details>

No, @grom72 ping

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/R/simple_client.c, line 44 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/16#-MkkXXGb5aq1CB__Wu41:-MklAIwLCn2PwJbcUYZ1:b32v57) ([raw file](https://github.com/ldorau/2021-04-21/blob/4bfe4bfb31102a3a9367a400a4daa85013814666/examples/R/simple_client.c#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Reminder:

```
/*
 * Limited by the maximum length of the private data
 * for rdma_connect() in case of RDMA_PS_TCP (28 bytes).
 */
```

Ref: https://github.com/pmem/fio/blob/rpma/engines/librpma_fio.h#L51
</blockquote></details>

+1

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16#-:-MklWKmA0ryKFO2ACMNI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/16#-:-MklXQ4t5LQkEiAO-5H9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
