### PR TITLE
example R: move MAX_USERS and PMEM_MIN_SIZE to server.c

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/34)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/34)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/R/server.c, line 18 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/34#-Mo3Ww5B0ByudQ9rqUMu:-Mo3Ww5B0ByudQ9rqUMv:b-1f6swy) ([raw file](https://github.com/ldorau/2021-04-21/blob/74b1a3bcd18f3b0e843c305e0cd0ea1639200ac3/examples/R/server.c#L18)):*
> ```C
> #define INIT_STR	"This is the initial server string."
> #define MAX_USERS	200
> #define PMEM_MIN_SIZE	(MAX_USERS * 4 * KILOBYTE) /* 4KiB for each user */
> ```

Please also remove these from the connection.h file.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/34)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/R/server.c, line 18 at r1](https://reviewable.io/reviews/ldorau/2021-04-21/34#-Mo3Ww5B0ByudQ9rqUMu:-Mo3mfNZ1xLgwHh7qdks:b-896fix) ([raw file](https://github.com/ldorau/2021-04-21/blob/74b1a3bcd18f3b0e843c305e0cd0ea1639200ac3/examples/R/server.c#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please also remove these from the connection.h file.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/34#-:-Mo3oqeX749v3jtgTEW8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/34#-:-Mo3aQO49P2RKMaEzVRr:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/34#-:-Mo3sbhsDB0y48U5P2M4:bg7igk9)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/2021-04-21/34#-:-Mo3tLluBDB4gzJW3TgC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
